main : com.allCommand.allCommand
name : plugin
version : 1.0.0
author : ceh
description : 테스트

commands:
  setHome:
    description: setHome
    usage: /setHome
    aliases: [setHome]
  goHome:
    description: goHome
    usage: /goHome
    aliases: [goHome]
  bank:
    description: 현금 관리 커맨드
    usage: /bank
    aliases: [bank]